import {addUser, deleteUser, showUser, login} from '../controllers/usercontroller.js';
import express from 'express';
import { authenticate,authorize } from '../middleware/auth.js';
// import { addProduct, showProduct } from '../controllers/productcontroller.js';
const userRoute = express.Router();
userRoute.get("/",authenticate,authorize("admin"),showUser);
userRoute.post("/signup",addUser);
userRoute.delete("/:id",authenticate,authorize("admin"),deleteUser);
userRoute.post("/login", login);
export default userRoute;